export const AUTH_START = "AUTH_START";
export const AUTH_FAILED = "AUTH_FAILED";
export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";
export const USER_LOGGEDOUT = "USER_LOGGEDOUT";
export const USER_CREATE = "USER_CREATE";
export const USER_FAIL = "USER_FAIL";
export const USER_SUBSCRIPTION = "USER_SUBSCRIPTION";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const FIRST_LOGIN = "FIRST_LOGIN";
export const AUTH_UPDATED = "AUTH_UPDATED";
export const AUTH_DEACTIVATED = "AUTH_DEACTIVATED";
export const AUTH_ACTIVATED = "AUTH_ACTIVATED";
export const EMAIL_UPDATE = "EMAIL_UPDATE";
export const EMAIL_VERIFY = "EMAIL_VERIFY";
export const NAME_UPDATE = "NAME_UPDATE";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const PASSWORD_UPDATE = 'PASSWORD_UPDATE';
export const GET_CURRENT_NAME = 'GET_CURRENT_NAME';

/*****GLOBAL STATE******/

export const RESET_STATE = "RESET_STATE";
export const FETCH_PROFESSION = "FETCH_PROFESSION";
export const FETCH_MEMBERS = "FETCH_MEMBERS";
export const FETCH_COUNTRY = "FETCH_COUNTRY";
export const FETCH_DASHBOARD_TIME_RANGE = "FETCH_DASHBOARD_TIME_RANGE";
export const FETCH_GRAPH_DATA = "FETCH_GRAPH_DATA";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const FETCH_MOBILE_GRAPH_DATA = "FETCH_MOBILE_GRAPH_DATA";
export const FETCH_ANALYZE_RESULT = "FETCH_ANALYZE_RESULT";

// *****UI*****

export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
export const OPEN_DROPDOWN = "OPEN_DROPDOWN";
export const CLOSE_DROPDOWN = "CLOSE_DROPDOWN";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const SET_MODAL_VIEW = "SET_MODAL_VIEW";
export const SET_SIDEBAR_VIEW = "SET_SIDEBAR_VIEW";
export const SET_USER_AVATAR = "SET_USER_AVATAR";
